<script setup>
import { onMounted, ref } from 'vue'
import { supabase } from '../supabase'
const props = defineProps({ user: Object, profile: Object })
const published = ref([]), mine = ref([]), submissions = ref([]), form = ref({ title: '', category: 'Book review', body: '' }), image = ref(null), message = ref(''), editing = ref(null), draft = ref({})
const load = async () => { const { data:p }=await supabase.from('blog_submissions').select('*').eq('status','published').order('created_at',{ascending:false});published.value=p||[];if(props.user){const {data}=await supabase.from('blog_submissions').select('*').eq('author_id',props.user.id).order('created_at',{ascending:false});mine.value=data||[]}if(props.profile?.role==='admin'){const {data}=await supabase.from('blog_submissions').select('*').order('created_at',{ascending:false});submissions.value=data||[]} }
const submit = async () => { if(!props.user)return message.value='Sign in to submit.';let image_url=null;if(image.value){const path=`${props.user.id}/${Date.now()}-${image.value.name}`;const {error}=await supabase.storage.from('blog-media').upload(path,image.value);if(error)return message.value=error.message;image_url=supabase.storage.from('blog-media').getPublicUrl(path).data.publicUrl}const {error}=await supabase.from('blog_submissions').insert([{author_id:props.user.id,author_name:props.profile?.username||'Member',title:form.value.title,category:form.value.category,body:form.value.body,image_url}]);if(error)return message.value=error.message;message.value='Received—your article is in review.';form.value={title:'',category:'Book review',body:''};load() }
const review=async(post,status)=>{const {error}=await supabase.from('blog_submissions').update({status}).eq('id',post.id);message.value=error?.message||`Article ${status}.`;load()}
const startEdit=post=>{editing.value=post.id;draft.value={title:post.title,category:post.category,body:post.body}}
const save=async()=>{const {error}=await supabase.from('blog_submissions').update(draft.value).eq('id',editing.value);message.value=error?.message||'Edits saved.';editing.value=null;load()}
onMounted(load)
</script>
<template>
<div><section class="rounded-[2rem] bg-[#6B1F36] p-10 text-white"><p class="text-xs uppercase tracking-widest text-[#F2BDC8]">The reading journal</p><h1 class="mt-3 font-display text-5xl">Stories from the quiet room.</h1></section>
<section v-if="published.length" class="mt-8 grid gap-4 md:grid-cols-3"><article v-for="post in published" :key="post.id" class="overflow-hidden rounded-2xl border bg-white p-6"><img v-if="post.image_url" :src="post.image_url" class="-mx-6 -mt-6 mb-4 h-40 w-[calc(100%+3rem)] object-cover"><p class="text-xs uppercase text-[#8A2945]">{{post.category}}</p><h2 class="mt-2 font-display text-2xl">{{post.title}}</h2><p class="mt-3 whitespace-pre-line text-sm text-[#6F6C66]">{{post.body}}</p></article></section>
<section class="mt-10 rounded-2xl border bg-white p-7"><h2 class="font-display text-3xl">Write for the reading journal.</h2><form @submit.prevent="submit" class="mt-5 grid gap-3"><input v-model="form.title" required placeholder="Article title" class="rounded-xl border p-3"><select v-model="form.category" class="rounded-xl border p-3"><option>Book review</option><option>Social commentary</option><option>Club reflection</option><option>Reading list</option></select><textarea v-model="form.body" required rows="6" placeholder="Write your piece…" class="rounded-xl border p-3"></textarea><label class="text-sm">Optional image<input type="file" accept="image/*" @change="image=$event.target.files?.[0]||null" class="mt-2 block"></label><button class="w-fit rounded-xl bg-[#6B1F36] px-5 py-3 text-xs uppercase text-white">Submit for review</button></form></section>
<section v-if="user&&mine.length" class="mt-10 rounded-2xl border bg-white p-7"><h2 class="font-display text-2xl">Your submissions</h2><div v-for="post in mine" :key="post.id" class="mt-3 flex justify-between rounded-xl bg-[#FBF0F1] p-4"><span>{{post.title}}</span><b class="text-xs uppercase text-[#8A2945]">{{post.status==='pending'?'Received — in review':post.status}}</b></div></section>
<section v-if="profile?.role==='admin'" class="mt-10 rounded-2xl border bg-white p-7"><p class="text-xs uppercase tracking-wide text-[#8A2945]">Editor desk</p><h2 class="mt-2 font-display text-3xl">Review submissions</h2><p v-if="message" class="mt-3 text-sm text-[#6B1F36]">{{message}}</p><article v-for="post in submissions" :key="post.id" class="mt-4 rounded-xl bg-[#FBF0F1] p-5"><p class="text-xs uppercase text-[#8A2945]">{{post.category}} · {{post.status}}</p><h3 class="font-display text-xl">{{post.title}}</h3><img v-if="post.image_url" :src="post.image_url" :alt="post.title" class="mt-3 h-48 w-full rounded-xl object-cover"><p class="mt-2 whitespace-pre-line text-sm">{{post.body}}</p><div class="mt-4 flex flex-wrap gap-2"><button @click="startEdit(post)" class="rounded-lg border border-[#6B1F36] px-3 py-2 text-xs text-[#6B1F36]">Edit</button><button @click="review(post,'published')" class="rounded-lg bg-[#6B1F36] px-3 py-2 text-xs text-white">Publish</button><button @click="review(post,'rejected')" class="rounded-lg border px-3 py-2 text-xs">Reject</button></div></article></section>
<div v-if="editing" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div class="w-full max-w-2xl rounded-2xl bg-white p-6"><h2 class="font-display text-2xl">Edit submission</h2><input v-model="draft.title" class="mt-4 w-full rounded border p-3"><select v-model="draft.category" class="mt-3 w-full rounded border p-3"><option>Book review</option><option>Social commentary</option><option>Club reflection</option><option>Reading list</option></select><textarea v-model="draft.body" rows="9" class="mt-3 w-full rounded border p-3"></textarea><div class="mt-4 flex gap-2"><button @click="save" class="rounded bg-[#6B1F36] px-4 py-2 text-xs text-white">Save edits</button><button @click="editing=null" class="rounded border px-4 py-2 text-xs">Cancel</button></div></div></div></div>
</template>
