-- Run this once in Supabase SQL Editor before using meetup management.

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to authenticated;

alter table public.meetup_sessions
  add column if not exists start_time time,
  add column if not exists capacity integer check (capacity > 0),
  add column if not exists is_archived boolean not null default false;

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.meetup_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'confirmed' check (status in ('confirmed', 'waitlisted')),
  created_at timestamptz not null default now(),
  unique (session_id, user_id)
);

alter table public.rsvps
  add column if not exists status text not null default 'confirmed'
  check (status in ('confirmed', 'waitlisted'));

alter table public.rsvps enable row level security;

drop policy if exists "Anyone can view RSVPs" on public.rsvps;
drop policy if exists "Members can RSVP for themselves" on public.rsvps;
drop policy if exists "Members or admins can cancel RSVP" on public.rsvps;

create policy "Anyone can view RSVPs"
on public.rsvps for select using (true);

create policy "Members can RSVP for themselves"
on public.rsvps for insert to authenticated
with check (user_id = auth.uid());

create policy "Members or admins can cancel RSVP"
on public.rsvps for delete to authenticated
using (user_id = auth.uid() or public.is_admin());

create table if not exists public.session_media (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.meetup_sessions(id) on delete cascade,
  image_url text not null,
  created_at timestamptz not null default now()
);

alter table public.session_media enable row level security;

drop policy if exists "Anyone can view session media" on public.session_media;
drop policy if exists "Admins can add session media" on public.session_media;
drop policy if exists "Admins can delete session media" on public.session_media;

create policy "Anyone can view session media"
on public.session_media for select using (true);

create policy "Admins can add session media"
on public.session_media for insert to authenticated
with check (public.is_admin());

create policy "Admins can delete session media"
on public.session_media for delete to authenticated
using (public.is_admin());

-- Lets admins document books that members forgot to add during a meetup.
alter table public.books enable row level security;

drop policy if exists "Admins can add archived meetup books" on public.books;

create policy "Admins can add archived meetup books"
on public.books for insert to authenticated
with check (public.is_admin());

insert into storage.buckets (id, name, public)
values ('meetup-media', 'meetup-media', true)
on conflict (id) do update set public = true;

drop policy if exists "Admins can upload meetup media" on storage.objects;
drop policy if exists "Admins can update meetup media" on storage.objects;
drop policy if exists "Admins can delete meetup media" on storage.objects;

create policy "Admins can upload meetup media"
on storage.objects for insert to authenticated
with check (bucket_id = 'meetup-media' and public.is_admin());

create policy "Admins can update meetup media"
on storage.objects for update to authenticated
using (bucket_id = 'meetup-media' and public.is_admin())
with check (bucket_id = 'meetup-media' and public.is_admin());

create policy "Admins can delete meetup media"
on storage.objects for delete to authenticated
using (bucket_id = 'meetup-media' and public.is_admin());
