create table if not exists public.blog_submissions (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  title text not null check (char_length(title) between 3 and 160),
  category text not null,
  body text not null check (char_length(body) between 40 and 10000),
  status text not null default 'pending' check (status in ('pending', 'published', 'rejected')),
  created_at timestamptz not null default now()
);

alter table public.blog_submissions enable row level security;

drop policy if exists "Members can submit blog articles" on public.blog_submissions;
drop policy if exists "Authors can view own blog submissions" on public.blog_submissions;
drop policy if exists "Admins can manage blog submissions" on public.blog_submissions;

create policy "Members can submit blog articles" on public.blog_submissions for insert to authenticated with check (author_id = auth.uid());
create policy "Authors can view own blog submissions" on public.blog_submissions for select to authenticated using (author_id = auth.uid());
create policy "Admins can manage blog submissions" on public.blog_submissions for all to authenticated using (public.is_admin()) with check (public.is_admin());
